Install OSMnx

In [1]:
!pip install osmnx

Collecting osmnx
  Downloading osmnx-2.1.0-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: geopandas>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from osmnx) (1.1.2)
Requirement already satisfied: networkx>=2.5 in /usr/local/lib/python3.12/dist-packages (from osmnx) (3.6.1)
Requirement already satisfied: numpy>=1.24 in /usr/local/lib/python3.12/dist-packages (from osmnx) (2.0.2)
Requirement already satisfied: pandas>=1.5 in /usr/local/lib/python3.12/dist-packages (from osmnx) (2.2.2)
Requirement already satisfied: requests>=2.30 in /usr/local/lib/python3.12/dist-packages (from osmnx) (2.32.4)
Requirement already satisfied: shapely>=2.0 in /usr/local/lib/python3.12/dist-packages (from osmnx) (2.1.2)
Requirement already satisfied: pyogrio>=0.7.2 in /usr/local/lib/python3.12/dist-packages (from geopandas>=1.0.1->osmnx) (0.12.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from geopandas>=1.0.1->osmnx) (26.0)
Requirement already satisfied: pyproj>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from geopandas>=1.0.1->osmnx) (3.7.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.5->osmnx) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.5->osmnx) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.5->osmnx) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30->osmnx) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30->osmnx) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30->osmnx) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30->osmnx) (2026.1.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.5->osmnx) (1.17.0)
Downloading osmnx-2.1.0-py3-none-any.whl (104 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.4/104.4 kB 5.8 MB/s eta 0:00:00
Installing collected packages: osmnx
Successfully installed osmnx-2.1.0

Import Libraries

In [11]:
import osmnx as ox
import pandas as pd

Select Study Area

In [10]:
place = "Nancy, France"

🔹 Experiment 1: Extract Amenities

In [12]:
import osmnx as ox

place = "Nancy, France"

tags_amenity = {"amenity": True}

gdf_amenity = ox.features_from_place(place, tags_amenity)

print("Number of amenities:", len(gdf_amenity))
gdf_amenity.head()

Number of amenities: 8651

                                   geometry         amenity collection_times  \
element id
node    262840256  POINT (6.16286 48.68721)        post_box      Mo-Sa 09:00
        309525299    POINT (6.1601 48.6884)       recycling              NaN
        313719091  POINT (6.16745 48.68585)  bicycle_rental              NaN
        313719092  POINT (6.17224 48.68686)  bicycle_rental              NaN
        313719095   POINT (6.1723 48.68959)  bicycle_rental              NaN

                    operator operator:wikidata     ref  \
element id
node    262840256   La Poste           Q373724  A1B3W9
        309525299        NaN               NaN     NaN
        313719091  Cyclocity          Q3008464      25
        313719092  Cyclocity          Q3008464      19
        313719095  Cyclocity          Q3008464      18

                                              source recycling:glass_bottles  \
element id
node    262840256                             survey                     NaN
        309525299  GrandNancy Orthophotographie 2012                     yes
        313719091                         GrandNancy                     NaN
        313719092                         GrandNancy                     NaN
        313719095  GrandNancy Orthophotographie 2012                     NaN

                  recycling_type   bicycle_rental  ... shelter_type  \
element id                                         ...
node    262840256            NaN              NaN  ...          NaN
        309525299      container              NaN  ...          NaN
        313719091            NaN  docking_station  ...          NaN
        313719092            NaN  docking_station  ...          NaN
        313719095            NaN  docking_station  ...          NaN

                  ref:FR:SDIS:EM_GRPT community monastery:type restriction  \
element id
node    262840256                 NaN       NaN            NaN         NaN
        309525299                 NaN       NaN            NaN         NaN
        313719091                 NaN       NaN            NaN         NaN
        313719092                 NaN       NaN            NaN         NaN
        313719095                 NaN       NaN            NaN         NaN

                  contact:housename payment:cheque type bicycle highway
element id
node    262840256               NaN            NaN  NaN     NaN     NaN
        309525299               NaN            NaN  NaN     NaN     NaN
        313719091               NaN            NaN  NaN     NaN     NaN
        313719092               NaN            NaN  NaN     NaN     NaN
        313719095               NaN            NaN  NaN     NaN     NaN

[5 rows x 407 columns]

🔹 Experiment 2: Extract Tourism Locations

In [14]:
tags_tourism = {"tourism": True}

gdf_tourism = ox.features_from_place(place, tags_tourism)

print("Number of tourism places:", len(gdf_tourism))
gdf_tourism.head()

Number of tourism places: 391

                                   geometry artwork_subject  artwork_type  \
element id
node    554228719   POINT (6.1808 48.69576)          Vierge     sculpture
        560041977   POINT (6.1865 48.69176)             NaN           NaN
        797799604    POINT (6.1843 48.6902)             NaN  installation
        960686099   POINT (6.1955 48.69411)             NaN           NaN
        1301182760  POINT (6.1952 48.69272)             NaN           NaN

                   material  source  tourism addr:housenumber  \
element id
node    554228719     stone  survey  artwork              NaN
        560041977       NaN     NaN    hotel               56
        797799604       NaN     NaN  artwork              NaN
        960686099       NaN  survey    hotel                9
        1301182760      NaN  survey    hotel                2

                               addr:street building:levels  check_date  ...  \
element id                                                              ...
node    554228719                      NaN             NaN         NaN  ...
        560041977   Place Monseigneur Ruch               4  2024-09-29  ...
        797799604                      NaN             NaN         NaN  ...
        960686099                      NaN             NaN  2024-12-31  ...
        1301182760                     NaN             NaN         NaN  ...

                   power_supply:fee shower surface tents water_point amenity  \
element id
node    554228719               NaN    NaN     NaN   NaN         NaN     NaN
        560041977               NaN    NaN     NaN   NaN         NaN     NaN
        797799604               NaN    NaN     NaN   NaN         NaN     NaN
        960686099               NaN    NaN     NaN   NaN         NaN     NaN
        1301182760              NaN    NaN     NaN   NaN         NaN     NaN

                   display contact:flickr seats barrier
element id
node    554228719      NaN            NaN   NaN     NaN
        560041977      NaN            NaN   NaN     NaN
        797799604      NaN            NaN   NaN     NaN
        960686099      NaN            NaN   NaN     NaN
        1301182760     NaN            NaN   NaN     NaN

[5 rows x 145 columns]

🔹 Experiment 3: Extract Shops

In [16]:
tags_shop = {"shop": True}

gdf_shop = ox.features_from_place(place, tags_shop)

print("Number of shops:", len(gdf_shop))
gdf_shop.head()

Number of shops: 1139

                                   geometry addr:housenumber   addr:street  \
element id
node    334523427    POINT (6.161 48.68513)               49  Rue de Laxou
        493347183  POINT (6.17177 48.68996)                2           NaN
        497670355  POINT (6.17642 48.68952)                2           NaN
        497677143  POINT (6.17738 48.68925)              NaN           NaN
        561144497  POINT (6.17853 48.69633)              NaN           NaN

                       brand brand:wikidata      contact:phone level  \
element id
node    334523427      Match        Q513977  +33 3 83 40 39 73     0
        493347183        NaN            NaN                NaN   NaN
        497670355  Printemps       Q1535260                NaN   NaN
        497677143       Paul       Q3370417                NaN   NaN
        561144497        NaN            NaN                NaN   NaN

                                name  \
element id
node    334523427              Match
        493347183                NaN
        497670355          Printemps
        497677143               Paul
        561144497  Le Petit Français

                                                   opening_hours operator  \
element id
node    334523427              Mo-Sa 08:00-21:00; Su 09:00-12:45    Match
        493347183                                            NaN      NaN
        497670355              Mo-Fr 10:00-19:00; Sa 10:00-19:30      NaN
        497677143              Mo-Fr 07:00-19:00; Sa 08:00-19:00      NaN
        561144497  Tu-Sa 10:00-13:00,15:00-19:30; Su 10:00-13:00      NaN

                   ... roof:shape fuel:e85 service indoor  \
element id         ...
node    334523427  ...        NaN      NaN     NaN    NaN
        493347183  ...        NaN      NaN     NaN    NaN
        497670355  ...        NaN      NaN     NaN    NaN
        497677143  ...        NaN      NaN     NaN    NaN
        561144497  ...        NaN      NaN     NaN    NaN

                  tickets:public_transport bakehouse produced_on_site room  \
element id
node    334523427                      NaN       NaN              NaN  NaN
        493347183                      NaN       NaN              NaN  NaN
        497670355                      NaN       NaN              NaN  NaN
        497677143                      NaN       NaN              NaN  NaN
        561144497                      NaN       NaN              NaN  NaN

                  contact:place type
element id
node    334523427           NaN  NaN
        493347183           NaN  NaN
        497670355           NaN  NaN
        497677143           NaN  NaN
        561144497           NaN  NaN

[5 rows x 197 columns]

Missing Values

In [17]:
print("Missing values in amenities:")
print(gdf_amenity.isnull().sum())

Missing values in amenities:
geometry                0
amenity                 0
collection_times     8595
operator             8072
operator:wikidata    8424
                     ...
contact:housename    8650
payment:cheque       8650
type                 8641
bicycle              8650
highway              8650
Length: 407, dtype: int64